DROP TABLE IF EXISTS "{ml_schema}"."stg_bureau_features";

CREATE TABLE "{ml_schema}"."stg_bureau_features" AS
WITH bureau_enriched AS (
    SELECT
        "SK_ID_CURR",
        "DAYS_CREDIT",
        "DAYS_CREDIT_ENDDATE",
        "DAYS_CREDIT_UPDATE",
        "DAYS_ENDDATE_FACT",
        "AMT_CREDIT_SUM",
        "AMT_CREDIT_SUM_DEBT",
        CASE
            WHEN "AMT_CREDIT_SUM" IS NULL OR "AMT_CREDIT_SUM" = 0 THEN NULL
            ELSE "AMT_CREDIT_SUM_DEBT" / "AMT_CREDIT_SUM"
        END AS debt_ratio,
        CASE
            WHEN "AMT_CREDIT_SUM" IS NULL OR "AMT_CREDIT_SUM_DEBT" IS NULL THEN NULL
            ELSE "AMT_CREDIT_SUM_DEBT" - "AMT_CREDIT_SUM"
        END AS debt_credit_diff
    FROM "{raw_schema}"."raw_bureau"
)
SELECT
    "SK_ID_CURR",
    MAX("DAYS_CREDIT") AS "recent_decision_bureau",
    AVG("DAYS_CREDIT") AS "BURO_DAYS_CREDIT_MEAN",
    SUM("DAYS_CREDIT") AS "BURO_DAYS_CREDIT_SUM",
    MAX("DAYS_CREDIT_ENDDATE") AS "BURO_DAYS_CREDIT_ENDDATE_MAX",
    SUM("DAYS_CREDIT_ENDDATE") AS "BURO_DAYS_CREDIT_ENDDATE_SUM",
    MAX("DAYS_CREDIT_UPDATE") AS "BURO_DAYS_CREDIT_UPDATE_MAX",
    VAR_SAMP("DAYS_CREDIT_UPDATE") AS "BURO_DAYS_CREDIT_UPDATE_VAR",
    AVG("DAYS_ENDDATE_FACT") AS "BURO_DAYS_ENDDATE_FACT_MEAN",
    MIN("DAYS_ENDDATE_FACT") AS "BURO_DAYS_ENDDATE_FACT_MIN",
    AVG("AMT_CREDIT_SUM_DEBT") AS "BURO_AMT_CREDIT_SUM_DEBT_MEAN",
    MAX(debt_credit_diff) AS "BURO_DEBT_CREDIT_DIFF_MAX",
    MIN(debt_credit_diff) AS "BURO_DEBT_CREDIT_DIFF_MIN",
    MAX(debt_ratio) AS "BURO_DEBT_RATIO_MAX",
    AVG(debt_ratio) AS "BURO_DEBT_RATIO_MEAN",
    SUM(debt_ratio) AS "BURO_DEBT_RATIO_SUM",
    VAR_SAMP(debt_ratio) AS "BURO_DEBT_RATIO_VAR"
FROM bureau_enriched
GROUP BY "SK_ID_CURR";

